### ISSUE TITLE
Errors when running the notebook

### ISSUE THREAD

**Issue by p-null** [yiaktan/NLP-Stock-Prediction#1]
Hi, thanks for sharing your work!

I have several errors when running your code.

Could you clone this repo and re-run it?

It is missing all_tickers_data.pkl file.
it gave error in Data_collection notebook because of this line
`df = pd.concat([df1,df2],axis=0)`. `df = df.reset_index()` also gives error.
Could you explain a little about the following code?
```
while part_no > no_parts:
    no_parts = int(input("Split data into how many parts?"))
    part_no = int(input("Which part is this?"))
```
    
Thank you!
Hope to hear from you soon!

**Comment by yiaktan** [comment]
Hi Tingkai! Thanks for finding my work. 

1. I've pushed a script called "download_financial_data.py", which should help you get the all_tickers_data.pkl.
2. Try using the doc_text_extract.py script to download the documents. The data collection notebook probably doesn't have the final version of code and can't be run as-is.
3. To scrape the docs faster and avoid memory issues, I ran several cloud instances simultaneously, splitting the list of tickers into x parts. The code block you copied tells the script which part of the ticker list to scrape docs from.

Hope it helps :) Feel free to ask more questions. Looking back I see this project could use some organizational improvements.
